### ISSUE TITLE
Volume...

### ISSUE THREAD

**Issue by Axxl07** [Jacoblightning/FlipperVideo#1]
Hi,
thanks a million for this helper, works perfectly !!
Just got a question about video volume....
Music of my video is really really weak, have to put an ear on flipper to listen it....
Is there a way to increase volume, maybe a line code in helper1.py ?
Was just wondering why and how to correct it...
Thanks if you have few minutes to answer me....
Once again, really good job ! Thanks !

**Comment by Jacoblightning** [comment]
Sorry, I've been meaning to reply but just kept forgetting. I'm aware of this issue and I think that it might be a power issue. WAV files play at a fine volume using the wav player so I will look into it.

**Comment by Axxl07** [comment]
Hey, thanks for your answer.....no worries ;-)
Found a personal solution : I have added a "filter volume" line in the audio process from your "Helper1.py".
Works perfectly for me...
You can easily increase or decrease the volume with the valor of filter volume. The more high is the number, the more loud is the sound...
In my example, 6 was perfect for me, a sound high enough and no saturation on Flipper.
Once again, thanks for your work ! Get a lot of troubles with "LTVA1/flipper-zero-video-player", impossible to finish to convert with Visual Studio...your script is really efficient !

**Comment by Jacoblightning** [comment]
Your welcome, feel free to submit a pull if you want and I'll look into it.

**Comment by Axxl07** [comment]
Ok, made one ;-)
Hope I've done things right, first pull request for me...

**Comment by Jacoblightning** [comment]
@Axxl07 I'm not seeing it. Did you draft it by mistake? If you can't find it, no worries, it's fine.

**Comment by Jacoblightning** [comment]
Ah, I see what you did. I merged it for you.

**Comment by Axxl07** [comment]
Ok, I've seen you changed helper1.py ;-)
Will be usefull for other users with volume troubles...
Thanks for all Jacob !
